# Generated by Django 4.1.4 on 2022-12-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_rename_state_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='location',
        ),
    ]
