# Generated by Django 4.1.4 on 2023-01-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_rename_state_city_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bandid',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='cityid',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='Genreid',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='venueid',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
