# Generated by Django 4.1.4 on 2023-01-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_band_bandid_city_cityid_genre_genreid_venue_venueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
