# Generated by Django 4.1.4 on 2023-01-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_band_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='band_sched',
            field=models.TextField(default='null'),
        ),
    ]
